jhradilek/asciidoctor-dita-vale

- fixtures/AuthorLine/ignore_attributes.adoc
- fixtures/AuthorLine/ignore_comments.adoc
- fixtures/AuthorLine/ignore_empty_line.adoc
- fixtures/AuthorLine/ignore_subsections.adoc
- fixtures/AuthorLine/report_author_line.adoc
- fixtures/AuthorLine/report_comments.adoc
- fixtures/AuthorLine/vale.ini
- styles/AsciiDocDITA/AuthorLine.yml
- test/AuthorLine.bats
> Add a rule to report accidental author lines

- fixtures/TaskSection/ignore_comments.adoc
- fixtures/TaskSection/ignore_other_modules.adoc
- fixtures/TaskSection/ignore_unknown_modules.adoc
- fixtures/TaskSection/report_content_type.adoc
- fixtures/TaskSection/report_module_type.adoc
- fixtures/TaskSection/report_sections.adoc
- fixtures/TaskSection/vale.ini
- styles/AsciiDocDITA/TaskSection.yml
- test/TaskSection.bats
> Add a rule to report sections in procedure modules

- fixtures/ContentType/ignore_content_type.adoc
- fixtures/ContentType/ignore_defined_type.adoc
- fixtures/ContentType/ignore_module_type.adoc
- fixtures/ContentType/report_comments.adoc
- fixtures/ContentType/report_missing_type.adoc
- fixtures/ContentType/report_missing_value.adoc
- fixtures/ContentType/vale.ini
- styles/AsciiDocDITA/ContentType.yml
- test/ContentType.bats
> Add a rule to report a missing content type definition

- fixtures/EntityReference/ignore_comments.adoc
- fixtures/EntityReference/ignore_numeric_references.adoc
- fixtures/EntityReference/ignore_supported_entities.adoc
- fixtures/EntityReference/report_entity_references.adoc
- fixtures/EntityReference/report_multiple_references.adoc
- fixtures/EntityReference/vale.ini
- styles/AsciiDocDITA/EntityReference.yml
- test/EntityReference.bats
Fixes issue #16.
I ended up using `script` because the `existence` check refused to properly report all entity references on a single line. I also suspect it had issues with ignoring word boundaries no matter what configuration I used.
> Add a rule to report unsupported character entity references

- fixtures/LineBreak/ignore_comments.adoc
- fixtures/LineBreak/report_line_break.adoc
- fixtures/LineBreak/vale.ini
- styles/AsciiDocDITA/LineBreak.yml
- test/LineBreak.bats
> Add a rule to report hard line breaks

- fixtures/DiscreteHeading/ignore_comments.adoc
- fixtures/DiscreteHeading/report_discrete_heading.adoc
- fixtures/DiscreteHeading/vale.ini
- styles/AsciiDocDITA/DiscreteHeading.yml
- test/DiscreteHeading.bats
> Add a vale rule to report discrete headings

- fixtures/NestedSection/ignore_comments.adoc
- fixtures/NestedSection/ignore_invalid_sections.adoc
- fixtures/NestedSection/ignore_valid_sections.adoc
- fixtures/NestedSection/report_nested_section.adoc
- fixtures/NestedSection/vale.ini
- styles/AsciiDocDITA/NestedSection.yml
- test/NestedSection.bats
> Add a vale rule to report level 2, 3, 4, and 5 sections

- fixtures/RelatedLinks/ignore_comments.adoc
- fixtures/RelatedLinks/ignore_other_sections.adoc
- fixtures/RelatedLinks/ignore_valid_lines.adoc
- fixtures/RelatedLinks/report_non_links.adoc
- fixtures/RelatedLinks/report_valid_sections.adoc
- fixtures/RelatedLinks/vale.ini
- styles/AsciiDocDITA/RelatedLinks.yml
- test/RelatedLinks.bats
> Add a rule to report non-link content in Additional resources.

- fixtures/TaskStep/ignore_attribute_lists.adoc
- fixtures/TaskStep/ignore_comments.adoc
- fixtures/TaskStep/ignore_other_sections.adoc
- fixtures/TaskStep/ignore_valid_lines.adoc
- fixtures/TaskStep/report_non_steps.adoc
- fixtures/TaskStep/vale.ini
- styles/AsciiDocDITA/TaskStep.yml
- test/TaskStep.bats
> Add a rule to report non-step elements in procedures

- fixtures/TaskStep/ignore_valid_lines.adoc
- styles/AsciiDocDITA/TaskStep.yml
> Do not report lines separated by an empty line if list continuation is present

- fixtures/TaskStep/ignore_conditionals.adoc
- styles/AsciiDocDITA/TaskStep.yml
- test/TaskStep.bats
> Do not report conditional statements

- fixtures/BlockTitle/ignore_block_titles.adoc
- fixtures/BlockTitle/ignore_comments.adoc
- fixtures/BlockTitle/ignore_procedue_titles.adoc
- fixtures/BlockTitle/ignore_steps.adoc
- fixtures/BlockTitle/report_block_titles.adoc
- fixtures/BlockTitle/vale.ini
- styles/AsciiDocDITA/BlockTitle.yml
- test/BlockTitle.bats
> Add a rule to report unsupported block titles

- fixtures/ExampleBlock/ignore_admonitions.adoc
- fixtures/ExampleBlock/ignore_comments.adoc
- fixtures/ExampleBlock/ignore_valid_examples.adoc
- fixtures/ExampleBlock/report_example_in_block.adoc
- fixtures/ExampleBlock/report_example_in_list.adoc
- fixtures/ExampleBlock/report_example_in_section.adoc
- fixtures/ExampleBlock/vale.ini
- styles/AsciiDocDITA/ExampleBlock.yml
- test/ExampleBlock.bats
> Add a rule to report invalid example blocks

- fixtures/BlockTitle/ignore_additional_resources.adoc
- styles/AsciiDocDITA/BlockTitle.yml
- test/BlockTitle.bats
> Issue #46: Do not report Additional resources as an invalid block title

- fixtures/ConditionalCode/ignore_comments.adoc
- fixtures/ConditionalCode/ignore_escapes.adoc
- fixtures/ConditionalCode/report_conditionals.adoc
- fixtures/ConditionalCode/vale.ini
- styles/AsciiDocDITA/ConditionalCode.yml
- test/ConditionalCode.bats
Conditional directives need to be resolved at conversion time. This rule gives the user an overview of all conditions that are present in the AsciiDoc file so that they can decide which attributes to supply during conversion.
> Add a rule to report conditional directives

- fixtures/TaskExample/ignore_admonitions.adoc
- fixtures/TaskExample/ignore_comments.adoc
- fixtures/TaskExample/ignore_other_modules.adoc
- fixtures/TaskExample/ignore_single_example.adoc
- fixtures/TaskExample/report_multiple_examples.adoc
- fixtures/TaskExample/vale.ini
- styles/AsciiDocDITA/TaskExample.yml
- test/TaskExample.bats
> Add a rule to report multiple examples in a procedure module

- README.md
- fixtures/TagDirective/report_comments.adoc
- fixtures/TagDirective/report_tags.adoc
- fixtures/TagDirective/vale.ini
- styles/AsciiDocDITA/TagDirective.yml
- test/TagDirective.bats
> Add a rule to report tag directives

- fixtures/ExampleBlock/ignore_admonitions.adoc
- fixtures/TaskExample/ignore_admonitions.adoc
- styles/AsciiDocDITA/ExampleBlock.yml
- styles/AsciiDocDITA/TaskExample.yml
> Issue #65: Do not report admonitions as invalid examples

- fixtures/BlockTitle/ignore_table_cells.adoc
- styles/AsciiDocDITA/BlockTitle.yml
- styles/AsciiDocDITA/TaskDuplicate.yml
- test/BlockTitle.bats
> Issue #74: Do not report cell formatting as a BlockTitle warning

- fixtures/TaskStep/ignore_block_titles.adoc
- fixtures/TaskStep/report_block_titles.adoc
- styles/AsciiDocDITA/TaskStep.yml
- test/TaskStep.bats
The `TaskStep` rule incorrectly failed to validate content that followed an unsupported block title in a procedure.
```asciidoc
:_mod-docs-content-type: PROCEDURE
.Procedure
. A valid step.
+
.A supported block title
|===
|A table cell
|===
An invalid line.
```
> Report content after unsupported block titles

- styles/AsciiDocDITA/BlockTitle.yml
- styles/AsciiDocDITA/TaskDuplicate.yml
- styles/AsciiDocDITA/TaskExample.yml
- styles/AsciiDocDITA/TaskSection.yml
- styles/AsciiDocDITA/TaskStep.yml
- styles/AsciiDocDITA/TaskTitle.yml
> Issue #89: Recognize content type separated by more than one space

- fixtures/RelatedLinks/ignore_attribute_references.adoc
- styles/AsciiDocDITA/RelatedLinks.yml
- test/RelatedLinks.bats
It is perfectly valid to define an entire link as a custom AsciiDoc attribute and then use that attribute reference in the related links. The `RelatedLinks` rule should not report these as problematic.
> Do not report bullet points with an attribute reference

- fixtures/TaskStep/ignore_example_block.adoc
- fixtures/TaskStep/report_admonitions.adoc
- styles/AsciiDocDITA/TaskStep.yml
- test/TaskStep.bats
> Issue #112: Do not report valid example blocks

- fixtures/BlockTitle/ignore_code_blocks.adoc
- styles/AsciiDocDITA/BlockTitle.yml
- test/BlockTitle.bats
The `BlockTitle` rule  incorrectly reports contents inside of code blocks. This pull request ensures that content in code blocks is completely ignored.
```
file.adoc
3:1  warning  Block titles can only be        AsciiDocDITA.BlockTitle  
assigned to examples, figures,                           
and tables in DITA.
```
```asciidoc
[source,terminal]
----
./run-command.sh .
----
```
> Do not report BlockTitle warnings for content in code blocks

- fixtures/TaskTitle/ignore_code_blocks.adoc
- styles/AsciiDocDITA/TaskTitle.yml
- test/TaskTitle.bats
The `TaskTitle` rule incorrectly reports contents inside of code blocks. This pull request ensures that content in code blocks is completely ignored.
```
file.adoc
5:1  warning  Unsupported titles cannot be    AsciiDocDITA.TaskTitle  
mapped to DITA tasks.
```
```asciidoc
:_mod-docs-content-type: PROCEDURE
[source,terminal]
----
./run-command.sh .
----
```
> Do not report TaskTitle warnings for content in code blocks

- fixtures/SidebarBlock/ignore_code_blocks.adoc
- fixtures/SidebarBlock/ignore_comments.adoc
- styles/AsciiDocDITA/SidebarBlock.yml
- test/SidebarBlock.bats
The `SidebarBlock` rule incorrectly reports contents inside of code blocks. This pull request ensures that content in code blocks is completely ignored.
```
file.adoc
4:1  warning  Sidebars are not supported in   AsciiDocDITA.SidebarBlock 
DITA.
```
```asciidoc
[source,terminal]
----
A code block.
*************
----
```
> Do not report SidebarBlock warnings for content in code blocks

- styles/AsciiDocDITA/AdmonitionTitle.yml
- styles/AsciiDocDITA/AttributeReference.yml
- styles/AsciiDocDITA/AuthorLine.yml
- styles/AsciiDocDITA/BlockTitle.yml
- styles/AsciiDocDITA/ConditionalCode.yml
- styles/AsciiDocDITA/ContentType.yml
- styles/AsciiDocDITA/DiscreteHeading.yml
- styles/AsciiDocDITA/EntityReference.yml
- styles/AsciiDocDITA/EquationFormula.yml
- styles/AsciiDocDITA/ExampleBlock.yml
- styles/AsciiDocDITA/IncludeDirective.yml
- styles/AsciiDocDITA/LineBreak.yml
- styles/AsciiDocDITA/LinkAttribute.yml
- styles/AsciiDocDITA/NestedSection.yml
- styles/AsciiDocDITA/PageBreak.yml
- styles/AsciiDocDITA/RelatedLinks.yml
- styles/AsciiDocDITA/ShortDescription.yml
- styles/AsciiDocDITA/SidebarBlock.yml
- styles/AsciiDocDITA/TableFooter.yml
- styles/AsciiDocDITA/TagDirective.yml
- styles/AsciiDocDITA/TaskDuplicate.yml
- styles/AsciiDocDITA/TaskExample.yml
- styles/AsciiDocDITA/TaskSection.yml
- styles/AsciiDocDITA/TaskStep.yml
- styles/AsciiDocDITA/TaskTitle.yml
- styles/AsciiDocDITA/ThematicBreak.yml
This was suggested in #121 and is an oversight on my part.
> Link to documentation from individual rules

- fixtures/LinkAttribute/ignore_escapes.adoc
- fixtures/LinkAttribute/report_attribute_references.adoc
- styles/AsciiDocDITA/LinkAttribute.yml
- test/LinkAttribute.bats
Fixes issue #104, specifically the situation where an inline link is not converted to a clickable link by Asciidoctor because of the presence of inline markup in the domain part. Contrary to the initial impression, whether such a link is marked up as inline code has no effect on whether it is resolved or not.
```asciidoc
https://_{ExampleURL}_:8443/path/_{ProjectName}_Path
https://*{ExampleURL}*:8443/path/_{ProjectName}_Path
https://`{ExampleURL}`:8443/path/_{ProjectName}_Path
https://#{ExampleURL}#:8443/path/_{ProjectName}_Path
https://~{ExampleURL}~:8443/path/_{ProjectName}_Path
https://^{ExampleURL}^:8443/path/_{ProjectName}_Path
https://_{ExampleSubdomain}_.example.com:8443/path/_{ProjectName}_Path
```
> Issue #104: Ignore links escaped with inline markup.
